<?php
// Language translations for Smart Chashi
// Usage: __('key') or get_text('key')

$languages = [
    'en' => [
        // Common
        'title' => 'Smart Chashi',
        'dashboard' => 'Dashboard',
        'crops' => 'Crops',
        'disease_detection' => 'Disease Detection',
        'chat' => 'Chat',
        'weather' => 'Weather',
        'marketplace' => 'Marketplace',
        'community' => 'Community',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'home' => 'Home',
        'login' => 'Login',
        'register' => 'Register',

        // Profile Page
        'your_profile' => 'Your Profile',
        'manage_account' => 'Manage your account and farming information',
        'personal_information' => 'Personal Information',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'email' => 'Email',
        'phone' => 'Phone',
        'account_type' => 'Account Type',
        'update_profile' => 'Update Profile',
        'farming_profile' => 'Farming Profile',
        'land_size' => 'Land Size (hectares)',
        'experience_level' => 'Experience Level',
        'beginner' => 'Beginner (0-2 years)',
        'intermediate' => 'Intermediate (2-5 years)',
        'advanced' => 'Advanced (5+ years)',
        'primary_crop' => 'Primary Crop',
        'region_district' => 'Region/District',
        'select' => 'Select...',
        'update_farming_info' => 'Update Farming Info',
        'security' => 'Security',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'confirm_password' => 'Confirm Password',
        'change_password' => 'Change Password',
        'account_statistics' => 'Account Statistics',
        'account_created' => 'Account Created',
        'last_login' => 'Last Login',
        'total_crops' => 'Total Crops Tracked',
        'chat_messages' => 'Chat Messages',
        'community_posts' => 'Community Posts',
        'preferences' => 'Preferences',
        'preferred_language' => 'Preferred Language',
        'theme' => 'Theme',
        'light' => 'Light',
        'dark' => 'Dark',
        'marketing_emails' => 'Marketing emails (new features, tips)',
        'product_updates' => 'Product updates and news',
        'save_preferences' => 'Save Preferences',
        'danger_zone' => 'Danger Zone',
        'delete_account' => 'Delete Account',
        'delete_account_warning' => 'Delete your account and all associated data. This action cannot be undone.',
        'english' => 'English',
        'bengali' => 'বাংলা',
        'language' => 'Language',
        'profile_photo' => 'Profile Photo',
        'change_photo' => 'Change Photo',
        
        // Home Page
        'smart_chashi' => 'Smart Chashi',
        'ai_farming_assistant' => 'AI Farming Assistant',
        'get_smart_farming' => 'Get smart farming advice & real-time weather alerts',
        'track_manage_crops' => 'Track & manage your crops',
        'manage' => 'Manage',
        'disease_check' => 'Disease Check',
        'detect_crop_diseases' => 'Detect crop diseases with AI',
        'check' => 'Check',
        'ask_farming_questions' => 'Ask farming questions',
        'realtime_weather' => 'Real-time weather & alerts',
        'view' => 'View',
        'buy_sell_products' => 'Buy & sell farm products',
        'browse' => 'Browse',
        'connect_farmers' => 'Connect with farmers',
        'join' => 'Join',
        'why_choose_smart_chashi' => 'Why Choose Smart Chashi?',
        'mobile_first_design' => 'Mobile-First Design',
        'mobile_first_desc' => 'Optimized for smartphones. Works perfectly on all devices with zero lag.',
        'secure_private' => 'Secure & Private',
        'secure_private_desc' => 'Your data is encrypted and secure. We respect your privacy completely.',
        'works_offline' => 'Works Offline',
        'works_offline_desc' => 'Access basic features even without internet connection. Syncs when you are back online.',
        'free_open' => 'Free & Open',
        'free_open_desc' => 'Basic features are free for all farmers. Premium options available for advanced features.',
        'bangla_support' => 'Bangla Support',
        'bangla_support_desc' => 'Available in both Bangla and English. AI chat supports your native language.',
        'always_updated' => 'Always Updated',
        'always_updated_desc' => 'New features added regularly. You always get the latest technology without waiting.',
        
        // Footer
        'about_smart_chashi' => 'About Smart Chashi',
        'footer_description' => 'AI-powered smart farming ecosystem to empower farmers with intelligent advice and real-time information.',
        'quick_links' => 'Quick Links',
        'contact' => 'Contact',
        'follow_us' => 'Follow Us',
        'all_rights_reserved' => 'All rights reserved',
        'version' => 'Version',
        
        // Dashboard
        'hi' => 'Hi',
        'welcome_dashboard' => 'Welcome to your farm dashboard',
        'alerts' => 'Alerts',
        'health' => 'Health',
        'location' => 'Location',
        'quick_links' => 'Quick Links',
        'your_crops' => 'Your Crops',
        'no_crops_yet' => 'No Crops Yet',
        'add_first_crop' => 'Add your first crop',
        
        // Crops Page
        'my_crops' => 'My Crops',
        'add_crop' => 'Add Crop',
        'crop_name' => 'Crop Name',
        'variety' => 'Variety',
        'area_hectares' => 'Area (hectares)',
        'planted_date' => 'Planted Date',
        'expected_harvest' => 'Expected Harvest',
        'status' => 'Status',
        'variety_eg' => 'e.g., BRRI dhan 28',
        'rice_wheat_etc' => 'Rice, Wheat, etc',
        'no_crops_added' => 'No Crops Added Yet',
        'add_first_crop_form' => 'Add your first crop using the form on the left to get started.',
        'delete' => 'Delete',
        'planted' => 'Planted',
        
        // Quick Actions
        'quick_actions' => 'Quick Actions',
        'detect_disease' => 'Detect Disease',
        'check_weather' => 'Check Weather',
        'sell_products' => 'Sell Products',
        
        // Disease Detection
        'analyze_photo' => 'Analyze Photo',
        'select_crop' => 'Select Crop',
        'choose_crop' => 'Choose crop',
        'upload_image' => 'Upload Image',
        'jpg_png_max' => 'JPG, PNG (Max 50MB)',
        'analyze' => 'Analyze',
        'how_to_use' => 'How to Use',
        'take_clear_photo' => 'Take a clear photo of affected area',
        'good_lighting' => 'Good lighting helps accuracy',
        'upload_get_results' => 'Upload and get results',
        'add_crop_first' => 'Add a crop first to analyze diseases',
        'take_photo' => 'Take Photo',
        'upload_from_device' => 'Upload from Device',
        'analyzing_image' => 'Analyzing Image',
        'please_wait' => 'Please wait while we analyze your plant...',
        'pro_tips' => 'Pro Tips',
        'focus_affected_area' => 'Focus on the affected area for better results',
        'natural_light_best' => 'Natural light provides the best accuracy',
        'multiple_angles_help' => 'Multiple angles can help identify disease',
        'capture_plant_image' => 'Capture Plant Image',
        'capture' => 'Capture',
        'cancel' => 'Cancel',
        'no_crops_yet' => 'No Crops Added Yet',
        'please_select_image' => 'Please select an image file',
        'camera_access_denied' => 'Unable to access camera. Please check permissions or use upload instead.',
        'please_select_crop' => 'Please select a crop',
        'please_upload_image' => 'Please capture or upload an image',
        'analysis_failed' => 'Analysis failed',
        'unknown_error' => 'Unknown error occurred',
        'error_analyzing_image' => 'Error analyzing image. Please try again.',
        'treatment_recommendations' => 'Treatment Recommendations',
        'confidence' => 'Confidence',
        'ai_powered_plant_disease_detection' => 'AI-Powered Plant Disease Detection',
        'drag_drop_or_click' => 'Drag & Drop or Click to Upload',
        'supports_jpg_png_max_5mb' => 'Supports JPG, PNG (Max 5MB)',
        'use_camera' => 'Use Camera',
        'choose_from_gallery' => 'Choose from Gallery',
        'analyze_now' => 'Analyze Now',
        'ai_is_detecting_diseases' => 'AI is detecting diseases in your plant image...',
        'how_it_works' => 'How It Works',
        'select_your_crop_from_list' => 'Select your crop from the list',
        'take_clear_photo_affected_area' => 'Take a clear photo of the affected area',
        'ai_analyzes_and_identifies' => 'AI analyzes and identifies the disease',
        'get_treatment_recommendations' => 'Get instant treatment recommendations',
        'use_natural_daylight' => 'Use natural daylight for best results',
        'focus_on_damaged_leaves' => 'Focus on damaged leaves or stems',
        'avoid_blurry_images' => 'Avoid blurry or dark images',
        'capture_multiple_symptoms' => 'Capture multiple symptoms if visible',
        'add_crop_before_disease_detection' => 'Please add a crop before using disease detection',
        'please_select_valid_image' => 'Please select a valid image file',
        'file_too_large_max_5mb' => 'File is too large. Maximum 5MB allowed',
        'please_upload_or_capture_image' => 'Please upload or capture an image',
        'high_risk' => 'High Risk',
        'medium_risk' => 'Medium Risk',
        'low_risk' => 'Low Risk',
        'confidence_level' => 'Confidence Level',
        'recommended_treatment' => 'Recommended Treatment',
        'analyze_another' => 'Analyze Another',
        'print_results' => 'Print Results',
        'optional' => 'Optional',
        'no_crop_selected' => 'No crop selected - General analysis',
        
        // Chat Page
        'chat_with_chashi' => 'Chat with Chashi',
        'ask_questions' => 'Ask Questions',
        'no_chat_history' => 'No chat history yet. Start asking!',
        'ask_about_crops' => 'Ask about crops, diseases, weather...',
        'send' => 'Send',
        'ask_about' => 'Ask About',
        'crop_management_tips' => 'Crop management & tips',
        'disease_identification' => 'Disease identification',
        'fertilizer_watering' => 'Fertilizer & watering',
        'weather_alerts' => 'Weather & alerts',
        'farm_equipment' => 'Farm equipment',
        
        // Weather Page
        'weather_alerts_title' => 'Weather & Alerts',
        'realtime_weather_info' => 'Real-time weather information and disaster alerts',
        'current_weather' => 'Current Weather',
        'humidity' => 'Humidity',
        'wind_speed' => 'Wind Speed',
        'rainfall' => 'Rainfall',
        'pressure' => 'Pressure',
        'your_region' => 'Your Region',
        'auto_detect_location' => 'Auto-Detect Location',
        'day_forecast' => '7-Day Forecast',
        'day' => 'Day',
        'condition' => 'Condition',
        'max_temp' => 'Max Temp',
        'min_temp' => 'Min Temp',
        'today' => 'Today',
        'tomorrow' => 'Tomorrow',
        
        // Marketplace
        'farm_marketplace' => 'Farm Marketplace',
        'buy_sell_direct' => 'Buy and sell farm products directly from farmers',
        'add_your_product' => 'Add Your Product',
        'product_name' => 'Product Name',
        'description' => 'Description',
        'price_per_unit' => 'Price per Unit (৳)',
        'quantity_available' => 'Quantity Available',
        'list_product' => 'List Product',
        'search_filter' => 'Search & Filter',
        'search_products' => 'Search products...',
        'filter_category' => 'Filter by Category',
        'filter_region' => 'Filter by Region',
        'all_categories' => 'All Categories',
        'all_regions' => 'All Regions',
        'available_products' => 'Available Products',
        'available' => 'Available',
        'contact_seller' => 'Contact Seller',
        
        // Community
        'farmer_community' => 'Farmer Community Forum',
        'share_experiences' => 'Share experiences, ask questions, and learn from other farmers',
        'monitor_engage_community' => 'Monitor and engage with the farming community',
        'create_new_post' => 'Create New Post',
        'post_official_advisory' => 'Post Official Advisory',
        'title' => 'Title',
        'whats_on_mind' => 'What\'s on your mind?',
        'category' => 'Category',
        'content' => 'Content',
        'share_experience' => 'Share your experience or question...',
        'post' => 'Post',
        'community_stats' => 'Community Stats',
        'total_farmers' => 'Total Farmers',
        'posts_today' => 'Posts Today',
        'active_discussions' => 'Active Discussions',
        'popular_topics' => 'Popular Topics',
        'recent_posts' => 'Recent Posts',
        'likes' => 'Likes',
        'reply' => 'Reply',
        
        // Community Tabs
        'community_posts_tab' => 'Community Posts',
        'nearby_farmers_tab' => 'Nearby Farmers',
        'officer_network_tab' => 'Officer Network',
        'farmers_in_my_region_tab' => 'Farmers in My Region',
        'community_analytics_tab' => 'Community Analytics',
        'my_bookmarks_tab' => 'My Bookmarks',
        
        // Community Categories
        'general_discussion' => 'General Discussion',
        'crop_problems' => 'Crop Problems',
        'best_practices' => 'Best Practices',
        'market_updates' => 'Market Updates',
        'weather_discussion' => 'Weather Discussion',
        'fertilizer_tips' => 'Fertilizer Tips',
        'official_advisory' => 'Official Advisory',
        'government_updates' => 'Government Updates',
        'training_programs' => 'Training Programs',
        
        // Photo Upload
        'add_photo_optional' => 'Add Photo (Optional)',
        'jpg_png_max_5mb' => 'JPG, PNG - Max 5MB',
        'photo_engagement_tip' => 'Adding a photo will help attract more engagement to your post',
        'remove_image' => 'Remove Image',
        
        // Filters & Sorting
        'filter_by' => 'Filter By',
        'all_categories' => 'All Categories',
        'sort_by' => 'Sort By',
        'newest_first' => 'Newest First',
        'oldest_first' => 'Oldest First',
        'most_popular' => 'Most Popular',
        'most_discussed' => 'Most Discussed',
        'refresh' => 'Refresh',
        
        // Loading & Empty States
        'loading' => 'Loading...',
        'loading_posts' => 'Loading posts...',
        'youve_reached_end' => 'You\'ve reached the end',
        'no_posts_found' => 'No posts found',
        'no_nearby_farmers' => 'No nearby farmers found. Try adjusting your search or distance filter.',
        'no_officers_found' => 'No officers found. Try adjusting your search.',
        'no_bookmarks_yet' => 'You haven\'t bookmarked any posts yet. Browse community posts and bookmark interesting ones!',
        
        // Pagination
        'first_page' => 'First Page',
        'previous_page' => 'Previous Page',
        'next_page' => 'Next Page',
        'last_page' => 'Last Page',
        'page' => 'Page',
        'of' => 'of',
        'showing' => 'Showing',
        'posts' => 'posts',
        
        // Search
        'search_by_name_location' => 'Search by name or location...',
        'search_posts' => 'Search posts by title or content...',
        'search' => 'Search',
        'clear' => 'Clear',
        'distance' => 'Distance',
        'km' => 'km',
        
        // Loading Indicators
        'loading_farmers' => 'Loading farmers...',
        'loading_officers' => 'Loading officers...',
        'loading_bookmarks' => 'Loading bookmarks...',
        
        // Section Titles
        'nearby_farmers' => 'Nearby Farmers',
        'officer_network' => 'Officer Network',
        'my_bookmarked_posts' => 'My Bookmarked Posts',
        
        // Modals
        'edit_post' => 'Edit Post',
        'save_changes' => 'Save Changes',
        'share_post' => 'Share Post',
        'share_this_post' => 'Share this post on:',
        'whatsapp' => 'WhatsApp',
        'facebook' => 'Facebook',
        'copy_link' => 'Copy Link',
        'share_url' => 'Share URL',
        
        // Login Page
        'login_to_smart_chashi' => 'Login to Smart Chashi',
        'access_dashboard' => 'Access your farming dashboard and manage your crops',
        'email_address' => 'Email Address',
        'password' => 'Password',
        'no_account' => 'Don\'t have an account?',
        'register_here' => 'Register here',
        'new_to_smart_chashi' => 'New to Smart Chashi?',
        'join_thousands' => 'Join thousands of farmers using AI-powered smart farming.',
        'key_features' => 'Key Features',
        'create_account' => 'Create Account',
        
        // Register Page
        'join_smart_chashi' => 'Join Smart Chashi',
        'create_farming_journey' => 'Create your account and start your smart farming journey',
        'already_account' => 'Already have an account?',
        'login_here' => 'Login here',
        'farmer' => 'Farmer',
        'agriculture_officer' => 'Agriculture Officer',
        'agree_terms' => 'I agree to the Terms of Service and Privacy Policy',
        'minimum_8_chars' => 'Minimum 8 characters',
        'reenter_password' => 'Re-enter password',
        
        // AI Agent Page
        'agent_page_title' => 'Smart Chashi - Your Expert Agricultural AI Assistant',
        'agent_tagline' => 'Ask your agricultural questions and get accurate AI-powered answers!',
        'agent_placeholder' => 'Enter your agricultural question here...',
        'voice_button' => 'Ask with Voice',
        'alert_title_voice_na' => 'Voice Not Available',
        'voice_text_reading' => 'Reading answer...',
        'detected_language' => 'Detected Language',
        'translated_query' => 'Translated Query',
        'error_connection' => 'Error: Could not connect to server. Please check your internet connection.',
        'stop_voice' => 'Stop Voice',
        
        // Officer Dashboard
        'officer_dashboard' => 'Agriculture Officer Dashboard',
        'welcome_officer' => 'Welcome',
        'monitor_support_farmers' => 'Monitor and Support Farmers',
        'your_oversight_stats' => 'Your Oversight Statistics',
        'total_farmers' => 'Total Farmers',
        'active_crops' => 'Active Crops',
        'reports_30d' => 'Reports (30d)',
        'alerts_7d' => 'Alerts (7d)',
        'officer_actions' => 'Officer Actions',
        'issue_alert' => 'Issue Alert',
        'send_alerts_farmers' => 'Send alerts to farmers in your region',
        'create_advisory' => 'Create Advisory',
        'create_publish_advisories' => 'Create and publish farming advisories',
        'schedule_visit' => 'Schedule Visit',
        'schedule_field_visits' => 'Schedule field visits to farmers',
        'find_farmer' => 'Find Farmer',
        'search_view_farmers' => 'Search and view farmer profiles',
        'search_farmers' => 'Search Farmers',
        'upcoming_field_visits' => 'Upcoming Field Visits',
        'date_time' => 'Date & Time',
        'farmer' => 'Farmer',
        'region' => 'Region',
        'purpose' => 'Purpose',
        'actions' => 'Actions',
        'mark_complete' => 'Mark Complete',
        'cancel_visit' => 'Cancel Visit',
        'no_upcoming_visits' => 'No upcoming field visits scheduled',
        'schedule_a_visit' => 'Schedule a Visit',
        'farmers_needing_attention' => 'Farmers Needing Attention',
        'high_severity_issues' => 'High Severity Issues',
        'last_issue' => 'Last Issue',
        'issues' => 'issues',
        'call' => 'Call',
        'view_profile' => 'View Profile',
        'recent_disease_detections' => 'Recent Disease Detections',
        'no_disease_detections' => 'No disease detections in the past 7 days',
        'crop' => 'Crop',
        'disease' => 'Disease',
        'severity' => 'Severity',
        'detected_on' => 'Detected On',
        'low' => 'Low',
        'medium' => 'Medium',
        'high' => 'High',
        'view_details' => 'View Details',
        'crops_by_region' => 'Crops by Region',
        'total' => 'Total',
        'active' => 'Active',
        'general_inspection' => 'General inspection',
        
        // Modal Forms
        'alert_type' => 'Alert Type',
        'weather_alert' => 'Weather Alert',
        'disease_alert' => 'Disease Alert',
        'market_alert' => 'Market Alert',
        'advisory' => 'Advisory',
        'system_alert' => 'System Alert',
        'priority' => 'Priority',
        'critical' => 'Critical',
        'enter_alert_title' => 'Enter alert title',
        'message' => 'Message',
        'enter_alert_message' => 'Enter detailed alert message',
        'target_region' => 'Target Region',
        'all_regions' => 'All Regions',
        'specific_farmer_optional' => 'Specific Farmer (Optional)',
        'all_farmers_in_region' => 'All Farmers in Region',
        'send_via' => 'Send Via',
        'app_notification' => 'App Notification',
        'email' => 'Email',
        'sms' => 'SMS',
        'all_channels' => 'All Channels',
        'cancel' => 'Cancel',
        'general' => 'General',
        'weather' => 'Weather',
        'seasonal' => 'Seasonal',
        'pest_control' => 'Pest Control',
        'irrigation' => 'Irrigation',
        'market' => 'Market',
        'enter_advisory_title' => 'Enter advisory title',
        'advisory_content' => 'Advisory Content',
        'enter_advisory_content' => 'Enter advisory content',
        'target_crops' => 'Target Crops',
        'all_crops' => 'All Crops',
        'applicable_regions' => 'Applicable Regions',
        'publish_advisory' => 'Publish Advisory',
        'visit_date' => 'Visit Date',
        'visit_time' => 'Visit Time',
        'optional' => 'Optional',
        'select_farmer' => 'Select Farmer',
        'select_farmer_to_visit' => 'Select a farmer to visit',
        'visit_purpose' => 'Visit Purpose',
        'enter_visit_purpose' => 'Enter purpose of visit',
        'notes' => 'Notes',
        'additional_notes' => 'Additional notes',
        'valid_from' => 'Valid From',
        'valid_to' => 'Valid To',
        'target_crops_comma' => 'Target Crops (comma separated)',
        'eg_rice_wheat' => 'e.g., Rice, Wheat, Tomato',
        'schedule_field_visit' => 'Schedule Field Visit',
        
        // Navbar - Officer
        'farmer_reports' => 'Farmer Reports',
        'issue_alerts' => 'Issue Alerts',
        
        // Home Page Stats
        'active_users' => 'Active Users',
        'farmers' => 'Farmers',
        'posts_shared' => 'Posts Shared',
        'login_to_access' => 'Login to access',
        'making_real_impact' => 'Making a Real Impact on Bangladesh Agriculture',
        'crops_tracked' => 'Crops Tracked',
        'diseases_detected' => 'Diseases Detected',
        'success_rate' => 'Success Rate',
        'ai_support' => 'AI Support',
        
        // Farmer Reports Page
        'monitor_respond_reports' => 'Monitor and respond to farmer disease reports and issues',
        'total_reports' => 'Total Reports',
        'critical_issues' => 'Critical Issues',
        'this_week' => 'This Week',
        'filter_reports' => 'Filter Reports',
        'all_severities' => 'All Severities',
        'apply_filters' => 'Apply Filters',
        'recent_reports' => 'Recent Reports',
        'no_reports_found' => 'No reports found matching your filters',
        'date' => 'Date',
        'disease' => 'Disease',
        'view' => 'View',
        
        // Issue Alert Page
        'create_manage_alerts' => 'Create and manage alerts to notify farmers about important issues',
        'create_new_alert' => 'Create New Alert',
        'alert_title' => 'Alert Title',
        'eg_severe_weather' => 'e.g., Severe Weather Warning',
        'select_type' => 'Select type...',
        'pest_outbreak' => 'Pest Outbreak',
        'disease_warning' => 'Disease Warning',
        'market_update' => 'Market Update',
        'government_notice' => 'Government Notice',
        'general_information' => 'General Information',
        'severity_level' => 'Severity Level',
        'info' => 'Info',
        'warning' => 'Warning',
        'alert_message' => 'Alert Message',
        'detailed_alert_message' => 'Detailed information about the alert...',
        'action_required' => 'Action Required (Optional)',
        'what_farmers_do' => 'What should farmers do?',
        'send_alert' => 'Send Alert',
        'clear' => 'Clear',
        'recent_alerts' => 'Recent Alerts',
        'no_alerts_created' => 'No alerts created yet',
        
        // Advisory Page
        'advisory_management' => 'Advisory Management',
        'create_publish_advisories_desc' => 'Create and publish farming advisories for farmers',
        'create_new_advisory' => 'Create New Advisory',
        'advisory_title' => 'Advisory Title',
        'eg_best_practices' => 'e.g., Best Practices for Rice Cultivation',
        'crop_type' => 'Crop Type',
        'select_category' => 'Select category...',
        'planting_sowing' => 'Planting & Sowing',
        'fertilizer_application' => 'Fertilizer Application',
        'pest_management' => 'Pest Management',
        'disease_control' => 'Disease Control',
        'harvesting' => 'Harvesting',
        'post_harvest' => 'Post-Harvest',
        'general_advice' => 'General Advice',
        'season' => 'Season',
        'all_seasons' => 'All Seasons',
        'rabi_winter' => 'Rabi (Winter)',
        'kharif_summer' => 'Kharif (Summer)',
        'monsoon' => 'Monsoon',
        'advisory_content' => 'Advisory Content',
        'detailed_advisory_info' => 'Detailed advisory information...',
        'key_recommendations' => 'Key Recommendations',
        'bullet_points_key' => 'Bullet points or key takeaways...',
        'publish_immediately' => 'Publish immediately',
        'my_published_advisories' => 'My Published Advisories',
        'no_advisories_published' => 'No advisories published yet',
    ],
    'bn' => [
        // Common
        'title' => 'স্মার্ট চাষী',
        'dashboard' => 'ড্যাশবোর্ড',
        'crops' => 'ফসলসমূহ',
        'disease_detection' => 'রোগ নির্ণয়',
        'chat' => 'চ্যাট',
        'weather' => 'আবহাওয়া',
        'marketplace' => 'বাজার',
        'community' => 'কমিউনিটি',
        'profile' => 'প্রোফাইল',
        'logout' => 'লগ আউট',
        'home' => 'হোম',
        'login' => 'লগইন',
        'register' => 'নিবন্ধন',

        // Profile Page
        'your_profile' => 'আপনার প্রোফাইল',
        'manage_account' => 'আপনার অ্যাকাউন্ট ও কৃষি সংক্রান্ত তথ্য পরিচালনা করুন',
        'personal_information' => 'ব্যক্তিগত তথ্য',
        'first_name' => 'নামের প্রথম অংশ',
        'last_name' => 'নামের শেষ অংশ',
        'email' => 'ইমেইল',
        'phone' => 'ফোন নম্বর',
        'account_type' => 'অ্যাকাউন্টের ধরন',
        'update_profile' => 'প্রোফাইল হালনাগাদ করুন',
        'farming_profile' => 'কৃষি প্রোফাইল',
        'land_size' => 'জমির পরিমাণ (হেক্টর)',
        'experience_level' => 'অভিজ্ঞতার স্তর',
        'beginner' => 'নবীন (০–২ বছর)',
        'intermediate' => 'মধ্যম (২–৫ বছর)',
        'advanced' => 'অভিজ্ঞ (৫+ বছর)',
        'primary_crop' => 'প্রধান ফসল',
        'region_district' => 'অঞ্চল / জেলা',
        'select' => 'নির্বাচন করুন',
        'update_farming_info' => 'কৃষি তথ্য হালনাগাদ করুন',
        'security' => 'নিরাপত্তা',
        'current_password' => 'বর্তমান পাসওয়ার্ড',
        'new_password' => 'নতুন পাসওয়ার্ড',
        'confirm_password' => 'পাসওয়ার্ড নিশ্চিত করুন',
        'change_password' => 'পাসওয়ার্ড পরিবর্তন',
        'account_statistics' => 'অ্যাকাউন্ট পরিসংখ্যান',
        'account_created' => 'অ্যাকাউন্ট তৈরির তারিখ',
        'last_login' => 'সর্বশেষ লগইন',
        'total_crops' => 'মোট ফসল সংখ্যা',
        'chat_messages' => 'চ্যাট বার্তা',
        'community_posts' => 'কমিউনিটি পোস্ট',
        'farmer_community' => 'কৃষক কমিউনিটি ফোরাম',
        'share_experiences' => 'অভিজ্ঞতা শেয়ার করুন, প্রশ্ন জিজ্ঞাসা করুন এবং অন্যান্য কৃষকদের কাছ থেকে শিখুন',
        'monitor_engage_community' => 'কৃষি সম্প্রদায়ের সাথে পর্যবেক্ষণ এবং সংযুক্ত হন',
        'create_new_post' => 'নতুন পোস্ট তৈরি করুন',
        'post_official_advisory' => 'সরকারি পরামর্শ পোস্ট করুন',
        'whats_on_mind' => 'আপনার মনে কি আছে?',
        'share_experience' => 'আপনার অভিজ্ঞতা বা প্রশ্ন শেয়ার করুন...',
        'community_stats' => 'কমিউনিটি পরিসংখ্যান',
        'posts_today' => 'আজকের পোস্ট',
        'active_discussions' => 'সক্রিয় আলোচনা',
        'popular_topics' => 'জনপ্রিয় বিষয়',
        'recent_posts' => 'সাম্প্রতিক পোস্ট',
        'likes' => 'লাইক',
        'reply' => 'উত্তর',
        'community_posts_tab' => 'কমিউনিটি পোস্ট',
        'nearby_farmers_tab' => 'কাছাকাছি কৃষক',
        'officer_network_tab' => 'কর্মকর্তা নেটওয়ার্ক',
        'farmers_in_my_region_tab' => 'আমার অঞ্চলের কৃষক',
        'community_analytics_tab' => 'কমিউনিটি বিশ্লেষণ',
        'my_bookmarks_tab' => 'আমার বুকমার্ক',
        'general_discussion' => 'সাধারণ আলোচনা',
        'crop_problems' => 'ফসল সমস্যা',
        'best_practices' => 'সর্বোত্তম অনুশীলন',
        'market_updates' => 'বাজার সংবাদ',
        'weather_discussion' => 'আবহাওয়া আলোচনা',
        'fertilizer_tips' => 'সার টিপস',
        'official_advisory' => 'সরকারি পরামর্শ',
        'government_updates' => 'সরকারি আপডেট',
        'training_programs' => 'প্রশিক্ষণ কর্মসূচি',
        'add_photo_optional' => 'ছবি যোগ করুন (ঐচ্ছিক)',
        'jpg_png_max_5mb' => 'JPG, PNG - সর্বোচ্চ ৫MB',
        'photo_engagement_tip' => 'একটি ছবি যোগ করলে আপনার পোস্টে আরও বেশি সংযুক্তি আকর্ষণ করতে সাহায্য করবে',
        'remove_image' => 'ছবি সরান',
        'filter_by' => 'ফিল্টার করুন',
        'all_categories' => 'সব বিভাগ',
        'sort_by' => 'সাজান',
        'newest_first' => 'নতুন প্রথমে',
        'oldest_first' => 'পুরাতন প্রথমে',
        'most_popular' => 'সবচেয়ে জনপ্রিয়',
        'most_discussed' => 'সবচেয়ে আলোচিত',
        'refresh' => 'রিফ্রেশ',
        'loading' => 'লোড হচ্ছে...',
        'loading_posts' => 'পোস্ট লোড হচ্ছে...',
        'youve_reached_end' => 'আপনি শেষে পৌঁছে গেছেন',
        'no_posts_found' => 'কোনও পোস্ট পাওয়া যায়নি',
        'no_nearby_farmers' => 'কাছাকাছি কোনও কৃষক পাওয়া যায়নি। আপনার অনুসন্ধান বা দূরত্ব ফিল্টার সামঞ্জস্য করার চেষ্টা করুন।',
        'no_officers_found' => 'কোনও কর্মকর্তা পাওয়া যায়নি। আপনার অনুসন্ধান সামঞ্জস্য করার চেষ্টা করুন।',
        'no_bookmarks_yet' => 'আপনি এখনও কোনও পোস্ট বুকমার্ক করেননি। কমিউনিটি পোস্ট ব্রাউজ করুন এবং আকর্ষণীয় পোস্ট বুকমার্ক করুন!',
        'first_page' => 'প্রথম পৃষ্ঠা',
        'previous_page' => 'আগের পৃষ্ঠা',
        'next_page' => 'পরবর্তী পৃষ্ঠা',
        'last_page' => 'শেষ পৃষ্ঠা',
        'page' => 'পৃষ্ঠা',
        'of' => 'এর',
        'showing' => 'প্রদর্শন',
        'posts' => 'পোস্ট',
        'search_by_name_location' => 'নাম বা অবস্থান দ্বারা অনুসন্ধান করুন...',
        'search_posts' => 'শিরোনাম বা বিষয়বস্তু দ্বারা পোস্ট অনুসন্ধান করুন...',
        'search' => 'অনুসন্ধান',
        'clear' => 'মুছুন',
        'distance' => 'দূরত্ব',
        'km' => 'কিমি',
        'loading_farmers' => 'কৃষক লোড হচ্ছে...',
        'loading_officers' => 'কর্মকর্তা লোড হচ্ছে...',
        'loading_bookmarks' => 'বুকমার্ক লোড হচ্ছে...',
        'nearby_farmers' => 'কাছাকাছি কৃষক',
        'officer_network' => 'কর্মকর্তা নেটওয়ার্ক',
        'my_bookmarked_posts' => 'আমার বুকমার্ক করা পোস্ট',
        'edit_post' => 'পোস্ট সম্পাদনা করুন',
        'save_changes' => 'পরিবর্তন সংরক্ষণ করুন',
        'share_post' => 'পোস্ট শেয়ার করুন',
        'share_this_post' => 'এই পোস্টটি শেয়ার করুন:',
        'whatsapp' => 'হোয়াটসঅ্যাপ',
        'facebook' => 'ফেসবুক',
        'copy_link' => 'লিংক কপি করুন',
        'share_url' => 'শেয়ার URL',
        'preferences' => 'পছন্দসমূহ',
        'preferred_language' => 'পছন্দের ভাষা',
        'theme' => 'থিম',
        'light' => 'হালকা',
        'dark' => 'গাঢ়',
        'marketing_emails' => 'বিপণন ইমেইল (নতুন ফিচার ও টিপস)',
        'product_updates' => 'পণ্য সংক্রান্ত আপডেট ও সংবাদ',
        'save_preferences' => 'পছন্দ সংরক্ষণ করুন',
        'danger_zone' => 'ঝুঁকিপূর্ণ এলাকা',
        'delete_account' => 'অ্যাকাউন্ট মুছে ফেলুন',
        'delete_account_warning' => 'এই কাজটি করলে আপনার অ্যাকাউন্ট ও সংশ্লিষ্ট সকল তথ্য স্থায়ীভাবে মুছে যাবে। এটি আর ফেরত আনা যাবে না।',
        'english' => 'ইংরেজি',
        'bengali' => 'বাংলা',
        'language' => 'ভাষা',
        'profile_photo' => 'প্রোফাইল ছবি',
        'change_photo' => 'ছবি পরিবর্তন করুন',

        // Home Page
        'smart_chashi' => 'স্মার্ট চাষী',
        'ai_farming_assistant' => 'এআই-ভিত্তিক কৃষি সহায়ক',
        'get_smart_farming' => 'স্মার্ট কৃষি পরামর্শ ও রিয়েল-টাইম আবহাওয়া সতর্কতা পান',
        'track_manage_crops' => 'আপনার ফসল সহজে ট্র্যাক ও পরিচালনা করুন',
        'manage' => 'পরিচালনা',
        // Quick Actions
        'quick_actions' => 'দ্রুত কার্যক্রম',
        'detect_disease' => 'রোগ শনাক্ত করুন',
        'check_weather' => 'আবহাওয়া দেখুন',
        'sell_products' => 'পণ্য বিক্রয় করুন',
        
        'disease_check' => 'রোগ পরীক্ষা',
        'detect_crop_diseases' => 'এআই ব্যবহার করে ফসলের রোগ শনাক্ত করুন',
        'analyze_photo' => 'ছবি বিশ্লেষণ করুন',
        'select_crop' => 'ফসল নির্বাচন করুন',
        'choose_crop' => 'ফসল বেছে নিন',
        'upload_image' => 'ছবি আপলোড করুন',
        'jpg_png_max' => 'JPG, PNG (সর্বোচ্চ 50MB)',
        'analyze' => 'বিশ্লেষণ করুন',
        'how_to_use' => 'কীভাবে ব্যবহার করবেন',
        'take_clear_photo' => 'ক্ষতিগ্রস্ত এলাকার স্পষ্ট ছবি তুলুন',
        'good_lighting' => 'ভালো আলোতে নির্ভুলতা বাড়ে',
        'upload_get_results' => 'আপলোড করুন এবং ফলাফল পান',
        'add_crop_first' => 'রোগ শনাক্তকরণ ব্যবহার করতে প্রথমে একটি ফসল যোগ করুন',
        'take_photo' => 'ছবি তুলুন',
        'upload_from_device' => 'ডিভাইস থেকে আপলোড করুন',
        'analyzing_image' => 'ছবি বিশ্লেষণ করা হচ্ছে',
        'please_wait' => 'অপেক্ষা করুন, আমরা আপনার গাছটি বিশ্লেষণ করছি...',
        'pro_tips' => 'বিশেষ পরামর্শ',
        'focus_affected_area' => 'ভালো ফলাফলের জন্য ক্ষতিগ্রস্ত এলাকায় ফোকাস করুন',
        'natural_light_best' => 'প্রাকৃতিক আলো সবচেয়ে ভালো নির্ভুলতা দেয়',
        'multiple_angles_help' => 'একাধিক কোণ থেকে ছবি তুললে রোগ শনাক্ত করতে সাহায্য হয়',
        'capture_plant_image' => 'গাছের ছবি তুলুন',
        'capture' => 'ক্যাপচার করুন',
        'cancel' => 'বাতিল করুন',
        'no_crops_yet' => 'এখনো কোনো ফসল যুক্ত করা হয়নি',
        'please_select_image' => 'একটি ছবি ফাইল নির্বাচন করুন',
        'camera_access_denied' => 'ক্যামেরা অ্যাক্সেস করতে অক্ষম। অনুগ্রহ করে অনুমতি পরীক্ষা করুন বা আপলোড ব্যবহার করুন।',
        'please_select_crop' => 'অনুগ্রহ করে একটি ফসল নির্বাচন করুন',
        'please_upload_image' => 'অনুগ্রহ করে একটি ছবি তুলুন বা আপলোড করুন',
        'analysis_failed' => 'বিশ্লেষণ ব্যর্থ হয়েছে',
        'unknown_error' => 'অজানা ত্রুটি ঘটেছে',
        'error_analyzing_image' => 'ছবি বিশ্লেষণ করতে ত্রুটি। আবার চেষ্টা করুন।',
        'treatment_recommendations' => 'চিকিৎসার সুপারিশ',
        'confidence' => 'আত্মবিশ্বাস',
        'ai_powered_plant_disease_detection' => 'এআই-চালিত উদ্ভিদ রোগ শনাক্তকরণ',
        'drag_drop_or_click' => 'ড্র্যাগ অ্যান্ড ড্রপ বা ক্লিক করে আপলোড করুন',
        'supports_jpg_png_max_5mb' => 'JPG, PNG সমর্থিত (সর্বোচ্চ ৫MB)',
        'use_camera' => 'ক্যামেরা ব্যবহার করুন',
        'choose_from_gallery' => 'গ্যালারি থেকে নির্বাচন করুন',
        'analyze_now' => 'এখনই বিশ্লেষণ করুন',
        'ai_is_detecting_diseases' => 'এআই আপনার গাছের ছবিতে রোগ শনাক্ত করছে...',
        'how_it_works' => 'এটি কীভাবে কাজ করে',
        'select_your_crop_from_list' => 'তালিকা থেকে আপনার ফসল নির্বাচন করুন',
        'take_clear_photo_affected_area' => 'ক্ষতিগ্রস্ত এলাকার স্পষ্ট ছবি তুলুন',
        'ai_analyzes_and_identifies' => 'এআই বিশ্লেষণ করে এবং রোগ শনাক্ত করে',
        'get_treatment_recommendations' => 'তাৎক্ষণিক চিকিৎসার সুপারিশ পান',
        'use_natural_daylight' => 'সেরা ফলাফলের জন্য প্রাকৃতিক আলো ব্যবহার করুন',
        'focus_on_damaged_leaves' => 'ক্ষতিগ্রস্ত পাতা বা কাণ্ডে ফোকাস করুন',
        'avoid_blurry_images' => 'ঘোলাটে বা অন্ধকার ছবি এড়িয়ে চলুন',
        'capture_multiple_symptoms' => 'দৃশ্যমান হলে একাধিক লক্ষণ ক্যাপচার করুন',
        'add_crop_before_disease_detection' => 'রোগ শনাক্তকরণ ব্যবহার করার আগে একটি ফসল যোগ করুন',
        'please_select_valid_image' => 'অনুগ্রহ করে একটি বৈধ ছবি ফাইল নির্বাচন করুন',
        'file_too_large_max_5mb' => 'ফাইলটি খুব বড়। সর্বোচ্চ ৫MB অনুমোদিত',
        'please_upload_or_capture_image' => 'অনুগ্রহ করে একটি ছবি আপলোড বা ক্যাপচার করুন',
        'high_risk' => 'উচ্চ ঝুঁকি',
        'medium_risk' => 'মাঝারি ঝুঁকি',
        'low_risk' => 'নিম্ন ঝুঁকি',
        'confidence_level' => 'আত্মবিশ্বাসের স্তর',
        'recommended_treatment' => 'প্রস্তাবিত চিকিৎসা',
        'analyze_another' => 'আরেকটি বিশ্লেষণ করুন',
        'print_results' => 'ফলাফল প্রিন্ট করুন',
        'optional' => 'ঘৈচ্ছিক',
        'no_crop_selected' => 'কোনো ফসল নির্বাচিত নয় - সাধারণ বিশ্লেষণ',
        
        'check' => 'পরীক্ষা করুন',
        'ask_farming_questions' => 'কৃষি বিষয়ক প্রশ্ন করুন',
        'realtime_weather' => 'রিয়েল-টাইম আবহাওয়া ও সতর্কতা',
        'view' => 'দেখুন',
        'buy_sell_products' => 'খামার পণ্য ক্রয় ও বিক্রয় করুন',
        'browse' => 'ব্রাউজ করুন',
        'connect_farmers' => 'অন্যান্য কৃষকের সাথে সংযুক্ত হন',
        'join' => 'যোগ দিন',
        'why_choose_smart_chashi' => 'কেন স্মার্ট চাষী ব্যবহার করবেন?',
        'mobile_first_design' => 'মোবাইল-ফার্স্ট ডিজাইন',
        'mobile_first_desc' => 'স্মার্টফোনের জন্য বিশেষভাবে অপ্টিমাইজ করা, সব ডিভাইসে সমানভাবে কার্যকর।',
        'secure_private' => 'নিরাপদ ও গোপনীয়',
        'secure_private_desc' => 'আপনার তথ্য সম্পূর্ণভাবে এনক্রিপ্টেড ও সুরক্ষিত রাখা হয়।',
        'works_offline' => 'অফলাইন ব্যবহারের সুবিধা',
        'works_offline_desc' => 'ইন্টারনেট ছাড়াই মৌলিক ফিচার ব্যবহার করুন, অনলাইনে এলে স্বয়ংক্রিয় সিঙ্ক হবে।',
        'free_open' => 'বিনামূল্যে ও উন্মুক্ত',
        'free_open_desc' => 'সকল কৃষকের জন্য মৌলিক সুবিধা বিনামূল্যে প্রদান করা হয়।',
        'bangla_support' => 'বাংলা ভাষা সমর্থন',
        'bangla_support_desc' => 'বাংলা ও ইংরেজি উভয় ভাষায় সম্পূর্ণ সহায়তা।',
        'always_updated' => 'নিয়মিত হালনাগাদ',
        'always_updated_desc' => 'নতুন ফিচার ও প্রযুক্তি নিয়মিত যুক্ত করা হয়।',
        
        // Footer
        'about_smart_chashi' => 'স্মার্ট চাষী সম্পর্কে',
        'footer_description' => 'এআই-ভিত্তিক স্মার্ট কৃষি সিস্টেম যা কৃষকদেরকে বুদ্ধিমান পরামর্শ ও রিয়েল-টাইম তথ্য দিয়ে ক্ষমতায়ন করে।',
        'quick_links' => 'দ্রুত লিংক',
        'contact' => 'যোগাযোগ',
        'follow_us' => 'ফলো করুন',
        'all_rights_reserved' => 'সকল অধিকার সংরক্ষিত',
        'version' => 'সংস্করণ',
        
        // Officer Dashboard
        'officer_dashboard' => 'কৃষি কর্মকর্তা ড্যাশবোর্ড',
        'welcome_officer' => 'স্বাগতম',
        'monitor_support_farmers' => 'কৃষকদের পর্যবেক্ষণ ও সহায়তা করুন',
        'your_oversight_stats' => 'আপনার তত্ত্বাবধান পরিসংখ্যান',
        'total_farmers' => 'মোট কৃষক',
        'active_crops' => 'সক্রিয় ফসল',
        'reports_30d' => 'রিপোর্ট (৩০ দিন)',
        'alerts_7d' => 'সতর্কতা (৭ দিন)',
        'officer_actions' => 'কর্মকর্তার কার্যক্রম',
        'issue_alert' => 'সতর্কতা জারি করুন',
        'send_alerts_farmers' => 'আপনার অঞ্চলের কৃষকদের সতর্কতা পাঠান',
        'create_advisory' => 'পরামর্শ তৈরি করুন',
        'create_publish_advisories' => 'কৃষি পরামর্শ তৈরি ও প্রকাশ করুন',
        'schedule_visit' => 'পরিদর্শন নির্ধারণ করুন',
        'schedule_field_visits' => 'কৃষকদের মাঠ পরিদর্শন নির্ধারণ করুন',
        'find_farmer' => 'কৃষক খুঁজুন',
        'search_view_farmers' => 'কৃষকদের খুঁজুন এবং প্রোফাইল দেখুন',
        'search_farmers' => 'কৃষক অনুসন্ধান',
        'upcoming_field_visits' => 'আসন্ন মাঠ পরিদর্শন',
        'date_time' => 'তারিখ ও সময়',
        'farmer' => 'কৃষক',
        'region' => 'অঞ্চল',
        'purpose' => 'উদ্দেশ্য',
        'actions' => 'কার্যক্রম',
        'mark_complete' => 'সম্পন্ন চিহ্নিত করুন',
        'cancel_visit' => 'পরিদর্শন বাতিল করুন',
        'no_upcoming_visits' => 'কোনো মাঠ পরিদর্শন নির্ধারিত নেই',
        'schedule_a_visit' => 'একটি পরিদর্শন নির্ধারণ করুন',
        'farmers_needing_attention' => 'মনোযোগ প্রয়োজন এমন কৃষক',
        'high_severity_issues' => 'উচ্চ মাত্রার সমস্যা',
        'last_issue' => 'সর্বশেষ সমস্যা',
        'issues' => 'সমস্যা',
        'call' => 'কল করুন',
        'view_profile' => 'প্রোফাইল দেখুন',
        'recent_disease_detections' => 'সাম্প্রতিক রোগ সনাক্তকরণ',
        'no_disease_detections' => 'গত ৭ দিনে কোনো রোগ সনাক্ত হয়নি',
        'crop' => 'ফসল',
        'disease' => 'রোগ',
        'severity' => 'তীব্রতা',
        'detected_on' => 'সনাক্ত হয়েছে',
        'low' => 'নিম্ন',
        'medium' => 'মাঝারি',
        'high' => 'উচ্চ',
        'view_details' => 'বিস্তারিত দেখুন',
        'crops_by_region' => 'অঞ্চল অনুযায়ী ফসল',
        'total' => 'মোট',
        'active' => 'সক্রিয়',
        'general_inspection' => 'সাধারণ পরিদর্শন',
        
        // Modal Forms
        'alert_type' => 'সতর্কতার ধরন',
        'weather_alert' => 'আবহাওয়া সতর্কতা',
        'disease_alert' => 'রোগ সতর্কতা',
        'market_alert' => 'বাজার সতর্কতা',
        'advisory' => 'পরামর্শ',
        'system_alert' => 'সিস্টেম সতর্কতা',
        'priority' => 'অগ্রাধিকার',
        'critical' => 'জরুরি',
        'enter_alert_title' => 'সতর্কতার শিরোনাম লিখুন',
        'message' => 'বার্তা',
        'enter_alert_message' => 'বিস্তারিত সতর্কতা বার্তা লিখুন',
        'target_region' => 'লক্ষ্য অঞ্চল',
        'all_regions' => 'সকল অঞ্চল',
        'specific_farmer_optional' => 'নির্দিষ্ট কৃষক (ঐচ্ছিক)',
        'all_farmers_in_region' => 'অঞ্চলের সকল কৃষক',
        'send_via' => 'প্রেরণ মাধ্যম',
        'app_notification' => 'অ্যাপ বিজ্ঞপ্তি',
        'email' => 'ইমেইল',
        'sms' => 'এসএমএস',
        'all_channels' => 'সকল মাধ্যম',
        'cancel' => 'বাতিল',
        'general' => 'সাধারণ',
        'weather' => 'আবহাওয়া',
        'seasonal' => 'মৌসুমী',
        'pest_control' => 'কীটপতঙ্গ নিয়ন্ত্রণ',
        'irrigation' => 'সেচ',
        'market' => 'বাজার',
        'enter_advisory_title' => 'পরামর্শের শিরোনাম লিখুন',
        'advisory_content' => 'পরামর্শের বিষয়বস্তু',
        'enter_advisory_content' => 'পরামর্শের বিষয়বস্তু লিখুন',
        'target_crops' => 'লক্ষ্য ফসল',
        'all_crops' => 'সকল ফসল',
        'applicable_regions' => 'প্রযোজ্য অঞ্চল',
        'publish_advisory' => 'পরামর্শ প্রকাশ করুন',
        'visit_date' => 'পরিদর্শনের তারিখ',
        'visit_time' => 'পরিদর্শনের সময়',
        'optional' => 'ঐচ্ছিক',
        'select_farmer' => 'কৃষক নির্বাচন করুন',
        'select_farmer_to_visit' => 'পরিদর্শনের জন্য একজন কৃষক নির্বাচন করুন',
        'visit_purpose' => 'পরিদর্শনের উদ্দেশ্য',
        'enter_visit_purpose' => 'পরিদর্শনের উদ্দেশ্য লিখুন',
        'notes' => 'নোট',
        'additional_notes' => 'অতিরিক্ত নোট',
        'valid_from' => 'বৈধ শুরু',
        'valid_to' => 'বৈধ শেষ',
        'target_crops_comma' => 'লক্ষ্য ফসল (কমা দ্বারা পৃথক)',
        'eg_rice_wheat' => 'যেমন, ধান, গম, টমেটো',
        'schedule_field_visit' => 'মাঠ পরিদর্শন নির্ধারণ করুন',
        
        // Navbar - Officer
        'farmer_reports' => 'কৃষক রিপোর্ট',
        'issue_alerts' => 'সতর্কতা জারি',
        
        // Home Page Stats
        'active_users' => 'সক্রিয় ব্যবহারকারী',
        'farmers' => 'কৃষক',
        'posts_shared' => 'শেয়ার করা পোস্ট',
        'login_to_access' => 'অ্যাক্সেস করতে লগইন করুন',
        'making_real_impact' => 'বাংলাদেশের কৃষিতে বাস্তব প্রভাব তৈরি করছি',
        'crops_tracked' => 'ট্র্যাক করা ফসল',
        'diseases_detected' => 'সনাক্ত রোগ',
        'success_rate' => 'সাফল্যের হার',
        'ai_support' => 'এআই সহায়তা',
        
        // Farmer Reports Page
        'monitor_respond_reports' => 'কৃষকদের রোগ রিপোর্ট ও সমস্যা পর্যবেক্ষণ ও প্রতিক্রিয়া জানান',
        'total_reports' => 'মোট রিপোর্ট',
        'critical_issues' => 'গুরুতর সমস্যা',
        'this_week' => 'এই সপ্তাহে',
        'filter_reports' => 'রিপোর্ট ফিল্টার করুন',
        'all_severities' => 'সব তীব্রতা',
        'apply_filters' => 'ফিল্টার প্রয়োগ করুন',
        'recent_reports' => 'সাম্প্রতিক রিপোর্ট',
        'no_reports_found' => 'আপনার ফিল্টারের সাথে মিলে এমন কোন রিপোর্ট পাওয়া যায়নি',
        'date' => 'তারিখ',
        'disease' => 'রোগ',
        'view' => 'দেখুন',
        
        // Issue Alert Page
        'create_manage_alerts' => 'কৃষকদের গুরুত্বপূর্ণ সমস্যা সম্পর্কে সতর্ক করতে সতর্কতা তৈরি ও পরিচালনা করুন',
        'create_new_alert' => 'নতুন সতর্কতা তৈরি করুন',
        'alert_title' => 'সতর্কতার শিরোনাম',
        'eg_severe_weather' => 'যেমন, তীব্র আবহাওয়া সতর্কতা',
        'select_type' => 'ধরন নির্বাচন করুন...',
        'pest_outbreak' => 'কীটপতঙ্গ প্রাদুর্ভাব',
        'disease_warning' => 'রোগ সতর্কতা',
        'market_update' => 'বাজার আপডেট',
        'government_notice' => 'সরকারি বিজ্ঞপ্তি',
        'general_information' => 'সাধারণ তথ্য',
        'severity_level' => 'তীব্রতার স্তর',
        'info' => 'তথ্য',
        'warning' => 'সতর্কতা',
        'alert_message' => 'সতর্কতা বার্তা',
        'detailed_alert_message' => 'সতর্কতা সম্পর্কে বিস্তারিত তথ্য...',
        'action_required' => 'প্রয়োজনীয় পদক্ষেপ (ঐচ্ছিক)',
        'what_farmers_do' => 'কৃষকদের কী করা উচিত?',
        'send_alert' => 'সতর্কতা পাঠান',
        'clear' => 'পরিষ্কার',
        'recent_alerts' => 'সাম্প্রতিক সতর্কতা',
        'no_alerts_created' => 'এখনও কোনো সতর্কতা তৈরি করা হয়নি',
        
        // Advisory Page
        'advisory_management' => 'পরামর্শ ব্যবস্থাপনা',
        'create_publish_advisories_desc' => 'কৃষকদের জন্য কৃষি পরামর্শ তৈরি ও প্রকাশ করুন',
        'create_new_advisory' => 'নতুন পরামর্শ তৈরি করুন',
        'advisory_title' => 'পরামর্শের শিরোনাম',
        'eg_best_practices' => 'যেমন, ধান চাষের সর্বোত্তম অনুশীলন',
        'crop_type' => 'ফসলের ধরন',
        'select_category' => 'বিভাগ নির্বাচন করুন...',
        'planting_sowing' => 'রোপণ ও বপন',
        'fertilizer_application' => 'সার প্রয়োগ',
        'pest_management' => 'কীটপতঙ্গ ব্যবস্থাপনা',
        'disease_control' => 'রোগ নিয়ন্ত্রণ',
        'harvesting' => 'ফসল সংগ্রহ',
        'post_harvest' => 'ফসল সংগ্রহ পরবর্তী',
        'general_advice' => 'সাধারণ পরামর্শ',
        'season' => 'মৌসুম',
        'all_seasons' => 'সব মৌসুম',
        'rabi_winter' => 'রবি (শীতকাল)',
        'kharif_summer' => 'খরিফ (গ্রীষ্মকাল)',
        'monsoon' => 'বর্ষাকাল',
        'advisory_content' => 'পরামর্শের বিষয়বস্তু',
        'detailed_advisory_info' => 'বিস্তারিত পরামর্শ তথ্য...',
        'key_recommendations' => 'মূল সুপারিশ',
        'bullet_points_key' => 'মূল পয়েন্ট বা সারসংক্ষেপ...',
        'publish_immediately' => 'অবিলম্বে প্রকাশ করুন',
        'my_published_advisories' => 'আমার প্রকাশিত পরামর্শ',
        'no_advisories_published' => 'এখনও কোনো পরামর্শ প্রকাশ করা হয়নি',
    ]

];

// Get current language
if (!function_exists('get_language')) {
    function get_language() {
        if (isset($_SESSION['language'])) {
            return $_SESSION['language'];
        }
        if (isset($_COOKIE['language'])) {
            return $_COOKIE['language'];
        }
        return 'en'; // Default language
    }
}

// Translate text
if (!function_exists('__')) {
    function __($key) {
        global $languages;
        $lang = get_language();
        
        if (isset($languages[$lang][$key])) {
            return $languages[$lang][$key];
        }
        return $languages['en'][$key] ?? $key;
    }
}

// Alias for __()
if (!function_exists('get_text')) {
    function get_text($key) {
        return __($key);
    }
}
